# Generated by Django 4.1.8 on 2023-05-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaillinkchecker', '0005_auto_20180922_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='email_recipient',
            field=models.EmailField(blank=True, default='', help_text='Recipient of the full problem report emails (page owners get reports too)', max_length=254),
        ),
        migrations.AddField(
            model_name='sitepreferences',
            name='email_sender',
            field=models.EmailField(default='noreply@regieorgaan-sia.nl', help_text='Sender of the problem report emails', max_length=254),
        ),
    ]
